### PR TITLE
Fully Functional GUI

### PR DESCRIPTION
**Pull request by RedSparr0w**
I know its a big PR but not sure how to put this into smaller PR's..
Fully Functional
Will probably need some tweeking but a good starting point.

Currently the "Cog" icon will open the Dev tools if needed
Amount of "New Items" down bottom left -> when clicked will clear notifications
Also countdown till refresh down bottom right

Have updated check for if app is owned as alot faster
from: `if(!client.ownsApp(appid))` | 120-180ms/app
to: `if(!client.picsCache.apps.hasOwnProperty(appid))` | 0-1ms/app

still needed to do:
- [ ] Add Icon | Use game icon in notification
- [ ] Maybe Popup a list for "New Games" rather than prompt's
- [ ] Add some options in "cog menu"
* Idle "> 2 hr apps" before "< 2 hr apps"
* Only idle 1 app at a time (no mass idle "< 2 hr apps")
* Max idle time per day/fortnight
* Idle specific apps along side card farming apps
* + More

### CODE REVIEW

**Comment by DoctorMcKay** [comment]
Looks good so far, thanks!

Can I question "Only idle 1 app at a time (no mass idle "< 2 hr apps")"? What do you mean by this?

**Comment by RedSparr0w** [comment]
If you have 2+ Apps with less than 2 hours, just idle 1 app at a time upto the 2 hour point (or until all cards recieved) as to avoid too much fake play time.

**Comment by DoctorMcKay** [comment]
You don't receive any cards until you have two hours on record. The most fake time that could be accrued on a particular app is 1.9 hours, and that's only if it was at 1.9 hours already and there was another app at 0. We could remove apps from our mass-idling list once they hit two hours perhaps...

**Comment by RedSparr0w** [comment]
but if you idle 20 "low hour apps" upto 2 hours, you will have 40 hours "fake play time" on your profile within 2 hours.
this way you could just slowly idle them as to only get 1 hour per hour of "fake play time".

Probably not really an option that would be used (and very low priority) but shouldn't be too hard to implement

**Comment by RedSparr0w** [comment]
Might not be a bad idea to remove apps from idling once they hit the 2 hour mark (if other apps are still below the 2 hour mark)

**Pull request merged**
