### PR TITLE
Package Scripts

### PR DESCRIPTION
**Pull request by RedSparr0w**
`npm install` - preinstall: Check if electron installed globally already / if not then install
`npm start` - start: will run "main" file

### CODE REVIEW

**Comment by DoctorMcKay** [comment]
:+1: Thanks

**Comment by RedSparr0w** [comment]
No Problem, although i think it may be worth looking at using nw.js instead of electron.

i myself have found it better to use

[but heres a fairly recent comparison](http://tangiblejs.com/posts/nw-js-and-electron-compared-2016-edition)

**Comment by DoctorMcKay** [comment]
Electron seems to be better supported, which is why I'm using it.

**Comment by RedSparr0w** [comment]
Fair enough, makes sense.

**Pull request merged**
